modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "better_client"
version = "${version}"
displayName = "Better Client"
authors = "ENC_Euphony"
description = '''
Make a better server experience
'''
logoFile = "icon.png"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.better_client]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_client]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,27)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_client]]
modId = "yet_another_config_lib_v3"
mandatory = true
type = "optional"
versionRange = "[3.9,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "better_client.mixins.json"
