modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "better_client"
version = "${version}"
displayName = "Better Client"
authors = "ENC_Euphony"
description = '''
Make a better server experience
'''
logoFile = "icon.png"

[[dependencies.better_client]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_client]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_client]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.better_client]]
modId = "yet_another_config_lib_v3"
mandatory = true
type = "required"
versionRange = "[3.6,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "better_client.mixins.json"
